name: .NET ビルド

on:
  push:
    branches-ignore:
      - releases
  pull_request:
    branches-ignore:
      - releases

jobs:
  build:
    name: .NET ビルド
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: .NET SDK をセットアップ
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: 依存関係を復元
        run: dotnet restore "**/*.sln"

      - name: ビルド
        run: dotnet build "**/*.sln" --configuration Release --no-restore
